name: comfyui

services:
  comfyui:
    build:
      context: .
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    security_opt:
      - no-new-privileges:true
    ports:
      - "8188:8188"
    volumes:
      - ./models:/comfy/models
      - ./input:/comfy/input
      - ./output:/comfy/output
      - ./workflows:/comfy/workflows
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0  # For RX 7900 GRE
      - PYTORCH_ROCM_ARCH=gfx1100        # For RX 7900 GRE
      - HSA_ENABLE_SDMA=0
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    shm_size: '8gb'
    # Optional: Limit resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: 16G
    #     reservations:
    #       memory: 8G
    restart: unless-stopped

volumes:
  models:
  input:
  output:
  workflows:
